### ISSUE TITLE
Pause on live stream at the beginning of the seekable range

### ISSUE THREAD

**Issue by jtrelak-vewd** [bbc/bigscreen-player#125]
I'm not sure if this is an issue. But I observed differences between playback of BBC CATAL and bigscreen-player. Some operations on live stream (slidingWindow live) does not work exactly like in CATAL. Does it mean, that CATAL has some additional logic to cover certain playback scenarios? 

Example: I clicked pause at the beginning of the seekable range
- on bigscreenPlayer playback is paused
- on CATAL: pause does not work at the beginning of the seekable range (playback is recovered immediately).

**Comment by tsadler1988** [comment]
Hi @jtrelak-vewd, CATAL uses Bigscreen Player, so behaviour should be consistent.

However, there is a known bug in `msestrategy` - the behaviour you are seeing in CATAL is correct, but `msestrategy` has not implemented this auto resume at start of window functionality.

Can you check what playback strategies you are using in both cases to confirm whether it is this known issue you are experiencing?

**Comment by tsadler1988** [comment]
Hi @jtrelak-vewd do you need anything further on this? #135 fixed the MSE bug, and there are other edge cases we've found and fixed around this.

**Comment by jtrelak-vewd** [comment]
Hi @tsadler1988 ,
Apologies for not answering your question, my oversight. Indeed - the problem was reproducible on MSE strategy. Thank you for taking care of this issue. We plan to test it more deeply, and use Bigscreen Player in more testing scenarios, I will let you know if there are any other playback issues here.

**Comment by tsadler1988** [comment]
Thanks @jtrelak-vewd, I'll close this issue.
