### ISSUE TITLE
JS error on trying to play live stream on TAL

### ISSUE THREAD

**Issue by jtrelak-vewd** [bbc/bigscreen-player#126]
I have done some tests of live streams on mse playback strategy successfully. Unfortunately I faced issues when I tried TAL strategy
When I try to set talstrategy (instead of mse), I have js error, and player doesn't work at all. I set it as follows:
window.bigscreenPlayer.playbackStrategy = 'talstrategy';

**Error message:**
TypeError: device.getLiveSupport is not a function
at Function.push../script/playbackstrategy/talstrategy.js.TALStrategy.getLiveSupport

Maybe there is any additional configuration needed to prevent such errors on TAL?

**Comment by tsadler1988** [comment]
Yes you need to be using Bigscreen Player within a TAL application for this to work - see https://github.com/bbc/bigscreen-player/wiki/Playback-Strategy#tal-strategy.

You should be able to use [nativestrategy](https://github.com/bbc/bigscreen-player/wiki/Playback-Strategy#native-strategy) without TAL, however (which our preferred way of doing non-MSE playback).

**Comment by jtrelak-vewd** [comment]
Hi Tom,
Thanks for your comment. It's my oversight, now it is clear for me. I'm closing this issue then.
