### ISSUE TITLE
State change / time callback names may not be unique

### ISSUE THREAD

**Issue by matt-stephenson** [bbc/bigscreen-player#14]
If a callback is unregistered from within the loop running the callbacks, problems can arise. 

An example of this was recently found when trying to listen only to the first PLAYING event, and therefore unregistering from within the callback.

This could be mitigated by running the state change callback in a backwards for loop rather than a foreach.

**Comment by jlks** [comment]
We can get this working as expected in a number of ways: 

in the mediaStateUpdateCallback:
```
stateChangeCallbacks.slice().forEach(function (callback) {
  callback(stateObject);
});
```

OR the backwards loop way...

OR

unregister for state changes:
```
stateChangeCallbacks = stateChangeCallbacks.filter(function (existingCallback) {
  return callback !== existingCallback;
});
```

I kinda prefer the first way. I don't like the idea of being able to mutate the data structure you're iterating through. This kinda solves it by giving you a copy whenever you want to iterate through it.

The last way is my second preferred option, but then its replacing the array as a whole...

If we could use ES6 this wouldn't be an issue, we could just use a Set.
