### ISSUE TITLE
Seek takes a long time if representation changes

### ISSUE THREAD

**Issue by dg-vewd** [bbc/bigscreen-player#191]
#### Environment
Browser: Google Chrome 87
Bigscreen Player: 4.6.0
Stream: default

#### Reproduction
Use stream with multiple representations. Continue seeking until seek takes noticeably long time ~5-10 seconds.

This is also observed in iPlayer and CATAL. The order of events that triggers this issue might be a little hard to achieve. It's much easier to reproduce with bandwidth throttling.

#### The issue
This is the order of events leading to the issue:

1. Seek to time _`t`_
2. Fragment with id _`i`_ for time _`t`_ is requested and download started
3. Before download is finished, there is drop in measured bandwidth and representation changes
4. The request for id _`i`_ is abandoned (because of quality change)

After this, next download request is for fragment with id _`i+1`_. New segments are downloaded and this continues for some time. Seek is ongoing because the fragment with time _`t`_ is missing.  Please see buffer ranges in attached log. It might take 5-10 seconds until the right fragment is requested again and playback finally starts.

This is the bug in dash.js and does not reproduce on dash reference player in version 3.2.1. Bigscreen Player is using older version of dash.js. From what I was able to find, changes that seem to fix the issue are introduced in version 3.1.2. This one in particular: [#3308](https://github.com/Dash-Industry-Forum/dash.js/pull/3308). Could you look into this?

#### Logs
[longseek.log](https://github.com/bbc/bigscreen-player/files/5855559/longseek.log)

**Comment by Luke-Chatburn** [comment]
@dg-vewd Thanks for providing such detailed information. As a team we are trying to come up with a solution that allows us to keep bigscreen-player more inline with the main dash.js.

**Comment by dg-vewd** [comment]
That's great! Let me know if you have any updates.

**Comment by dg-vewd** [comment]
Hello @Luke-Chatburn, are you be able to tell us when the issue could be handled, even a rough estimation would be helpful.

**Comment by Luke-Chatburn** [comment]
@dg-vewd Sorry, this should be picked up soon. If I get a more accurate time scale I will try and update here.

**Comment by domjacks** [comment]
@dg-vewd Hi. We've now released an updated version of bigscreen-player along with Dash.js v3.2.0. 

Let me know if this resolved your issues 😄

**Comment by dg-vewd** [comment]
Hi! I can no longer reproduce this issue with new version of bigscreen-player. Thanks a lot :smiley:
