### ISSUE TITLE
Workaround when seeking in MSE strategy

### ISSUE THREAD

**Issue by matt-stephenson** [bbc/bigscreen-player#4]
https://github.com/bbc/bigscreen-player/blob/df6e3da0c200cd397074691f7f5edf8a4056c72f/script/playbackstrategy/msestrategy.js#L271

This is a workaround based on the windowType being sliding. Sliding here refers to the DASH manifest having a timeShiftBufferDepth value.

Ultimately when seeking, dashjs will set the current time on the underlying video element. However, something else, either in dashjs, or our interaction with it, was causing problems when seeking and the manifest has a timeShiftBufferDepth.

Therefore this workaround bypasses the dash media player seek code and sets the time directly on the video element.

It would be good to investigate this and ideally use the `mediaPlayer.seek` in all cases.

**Comment by jlks** [comment]
Fixed with #111
