### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [bbc/bigscreen-player#46]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by tsadler1988** [comment]
@anharismail thank you for the offer, but unfortunately we are not in a position where we could accept that sort of contribution. Our designers will be creating a logo for us in due course.
