### ISSUE TITLE
Properly document API and internal functions

### ISSUE THREAD

**Issue by magnuswoody** [bbc/bigscreen-player#54]
`bigscreen-player` is considered self documented by understanding the code when reading through. More thorough [docma](https://www.npmjs.com/package/docma) styling could be used to improve the ease of contributors - as well as tidy up the code base.

**Comment by domjacks** [comment]
We did some work recently to publish documentation using JSDocs along with some of our tutorials. 

We should improve our documentation over time when modifying the codebase 😄
