### ISSUE TITLE
Point of truth for getting started

### ISSUE THREAD

**Issue by magnuswoody** [bbc/bigscreen-player#89]
The README should point to a singular point of truth for getting started with `bigscreen-player`. At the minute a lot of information is contained within the README that could be migrated to the wiki, or directly refer to the example app for more details. 

Currently, this requires updating the README and the wiki separately if a public facing aspect of `bigscreen-player` is changed.

**Comment by domjacks** [comment]
This should be solved with the work done to create the new docs microsite #246 

https://bbc.github.io/bigscreen-player/api/tutorial-Getting%20Started.html
